### ISSUE TITLE
Blocking in .xonshrc

### ISSUE THREAD

**Issue by alecandido** [willsALMANJ/xontrib-autojump#10]
When attempting to start xonsh with the following simple .xonshrc it never ends (or at least it's taking a lot):

```py
xontrib load autojump
```

When blocked with Ctrl+C it emits the following traceback:
<details><summary>Traceback</summary>
<pre>
^CTraceback (most recent call last):
  File "/home/alessandro/.local/bin/xonsh", line 8, in <module>
    sys.exit(main())
  File "/home/alessandro/.local/lib/python3.8/site-packages/xonsh/main.py", line 419, in main
    args = premain(argv)
  File "/home/alessandro/.local/lib/python3.8/site-packages/xonsh/main.py", line 355, in premain
    env = start_services(shell_kwargs, args)
  File "/home/alessandro/.local/lib/python3.8/site-packages/xonsh/main.py", line 305, in start_services
    xonshrc_context(rcfiles=rc, execer=execer, ctx=ctx, env=env, login=login)
  File "/home/alessandro/.local/lib/python3.8/site-packages/xonsh/environ.py", line 2206, in xonshrc_context
    status = xonsh_script_run_control(rcfile, ctx, env, execer=execer, login=login)
  File "/home/alessandro/.local/lib/python3.8/site-packages/xonsh/environ.py", line 2243, in xonsh_script_run_control
    run_script_with_cache(filename, execer, ctx)
  File "/home/alessandro/.local/lib/python3.8/site-packages/xonsh/codecache.py", line 162, in run_script_with_cache
    run_compiled_code(ccode, glb, loc, mode)
  File "/home/alessandro/.local/lib/python3.8/site-packages/xonsh/codecache.py", line 67, in run_compiled_code
    func(code, glb, loc)
  File "/home/alessandro/.xonshrc", line 4, in <module>
    xontrib load autojump
  File "/home/alessandro/.local/lib/python3.8/site-packages/xonsh/built_ins.py", line 1052, in subproc_captured_hiddenobject
    return run_subproc(cmds, captured="hiddenobject", envs=envs)
  File "/home/alessandro/.local/lib/python3.8/site-packages/xonsh/built_ins.py", line 1011, in run_subproc
    command.end()
  File "/home/alessandro/.local/lib/python3.8/site-packages/xonsh/proc.py", line 2150, in end
    self._end(tee_output=tee_output)
  File "/home/alessandro/.local/lib/python3.8/site-packages/xonsh/proc.py", line 2158, in _end
    for _ in self.tee_stdout():
  File "/home/alessandro/.local/lib/python3.8/site-packages/xonsh/proc.py", line 2071, in tee_stdout
    for line in self.iterraw():
  File "/home/alessandro/.local/lib/python3.8/site-packages/xonsh/proc.py", line 1959, in iterraw
    proc.wait()
  File "/home/alessandro/.local/lib/python3.8/site-packages/xonsh/proc.py", line 1737, in wait
    r = self.f(self.args, stdin, stdout, stderr, spec, spec.stack)
  File "/home/alessandro/.local/lib/python3.8/site-packages/xonsh/proc.py", line 1232, in proxy_two
    return f(args, stdin)
  File "/home/alessandro/.local/lib/python3.8/site-packages/xonsh/xontribs.py", line 217, in xontribs_main
    return _MAIN_XONTRIB_ACTIONS[ns.action](ns)
  File "/home/alessandro/.local/lib/python3.8/site-packages/xonsh/xontribs.py", line 137, in _load
    return xontribs_load(ns.names, verbose=ns.verbose)
  File "/home/alessandro/.local/lib/python3.8/site-packages/xonsh/xontribs.py", line 124, in xontribs_load
    update_context(name, ctx=ctx)
  File "/home/alessandro/.local/lib/python3.8/site-packages/xonsh/xontribs.py", line 69, in update_context
    modctx = xontrib_context(name)
  File "/home/alessandro/.local/lib/python3.8/site-packages/xonsh/xontribs.py", line 35, in xontrib_context
    m = importlib.import_module(spec.name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/alessandro/.local/lib/python3.8/site-packages/xontrib/autojump.xsh", line 122, in <module>
    _autojump_xonsh()
  File "/home/alessandro/.local/lib/python3.8/site-packages/xontrib/autojump.xsh", line 117, in _autojump_xonsh
    if !(completer list|grep autojump):
  File "/home/alessandro/.local/lib/python3.8/site-packages/xonsh/proc.py", line 1914, in __bool__
    return self.returncode == 0
  File "/home/alessandro/.local/lib/python3.8/site-packages/xonsh/proc.py", line 2354, in returncode
    self.end()
  File "/home/alessandro/.local/lib/python3.8/site-packages/xonsh/proc.py", line 2150, in end
    self._end(tee_output=tee_output)
  File "/home/alessandro/.local/lib/python3.8/site-packages/xonsh/proc.py", line 2158, in _end
    for _ in self.tee_stdout():
  File "/home/alessandro/.local/lib/python3.8/site-packages/xonsh/proc.py", line 2071, in tee_stdout
    for line in self.iterraw():
  File "/home/alessandro/.local/lib/python3.8/site-packages/xonsh/proc.py", line 1957, in iterraw
    task = wait_for_active_job()
  File "/home/alessandro/.local/lib/python3.8/site-packages/xonsh/jobs.py", line 208, in wait_for_active_job
    _, wcode = os.waitpid(obj.pid, os.WUNTRACED)
KeyboardInterrupt
</pre></details>

**Comment by wshanks** [comment]
The hang is due to https://github.com/xonsh/xonsh/issues/3725. This has been addressed in the repo here. Please try the latest version of autojump.xsh in the `main` branch. I don't have control of the PyPI package at the moment.

**Comment by alecandido** [comment]
Ok sorry, so it's just the PyPI package that is broken. I tested with `main` and everything is actually working

**Comment by wshanks** [comment]
No problem. This reminded me that I had meant to try to get control of the PyPI repo. We will see what happens with pypa/pypi-support#854.
